config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users,
               :path => '', 
               :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
               :controllers=>{:registrations=> 'registrations'}
  

   root 'pages#home'
  
  resources :users, only: [:show]
  resources :rooms,  path: 'annonces' do 
    resources :reservations, only: [:create]
    resources :reviews, only: [:create, :destroy]
  end
  resources :photos
  
  
  get 'your_trips' => 'reservations#your_trips', path: 'mes_voyages'
  get 'your_reservations' => 'reservations#your_reservations', path: 'mes_reservations'

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :room
  
   has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, 
   :default_url => "/assets/images/profil.png"
   validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :user
  belongs_to :room
end

app/models/reserversation.rb
class Reserversation < ActiveRecord::Base
  belongs_to :user
  belongs_to :room
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :room
  belongs_to :user
end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :user
  has_many :photos
  has_many :reservations
  has_many :reviews
  
  validates :home_type, presence: true 
 
   validates :room_type, presence: true
 
   validates :accommodate, presence: true
 
   validates :bed_room, presence: true
 
   validates :bath_room, presence: true
 
   validates :listing_name, presence: true, length: {maximum: 75} 
               
   validates :summary, presence: true, length: {maximum: 600}
 
   validates :address, presence: true
 
   validates :price, numericality: { only_integer: true, greater_than: 5 } 
              
   geocoded_by :address
   
   after_validation :geocode, if: :address_changed?
  
  def average_rating
    reviews.count == 0 ? 0 : reviews.average(:star).round(2)
  end
  
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  validates :fullname, presence: true, length: { maximum: 65}
  
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, 
  :default_url => "/assets/images/profil.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  
  has_many :rooms
  has_many :reservations
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
protect_from_forgery with: :exception
before_action :configure_permitted_parameters, if: :devise_controller?
 
protected
def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:fullname])
    devise_parameter_sanitizer.permit(:account_update, keys: [:fullname, :avatar, :phone_number, :description, :email, :password, :password_confirmation])
end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  end
  
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  
  def destroy
    @photo = Photo.find(params[:id])
    room = @photo.room
    
    @photo.destroy
    
    @photos = Photo.where(room_id: room.id)
    
    respond_to :js
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController  < Devise::RegistrationsController
    
  protected
  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
 
before_action :authenticate_user! 



  
def create
 
      @reservation = current_user.reservations.create(reservation_params)       
      redirect_to @reservation.room, notice: " Votre réservation a été acceptée "
end
 
def your_trips
  @trips = current_user.reservations
end
  
def your_reservations
  
    @rooms = current_user.rooms
end
  
private
 
     def reservation_params         
        params.require(:reservation).permit(:start_date, :end_date, :price, :total, :room_id)     
     end 
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  
  def create
       @review = current_user.reviews.create(review_params)
       redirect_to @review.room
   end
   
   def destroy
       @review = Review.find(params[:id])
       room = @review.room
       @review.destroy
       redirect_to room
   end
   
   private
   def review_params
       params.require(:review).permit(:comment, :star, :room_id)
   end
  
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  
  before_action :set_room, only: [:show, :edit, :update]
  before_action :authenticate_user!, except:[:show]
  before_action :require_same_user, only: [:edit, :update]
  
  def index
    @rooms = current_user.rooms
  end
  
  def show
    @photos = @room.photos
    
    @booked = Reservation.where("room_id = ? AND user_id = ?", @room.id, current_user.id).present?
    
    if current_user
      @reviews = @room.reviews
      @hasReview = @reviews.find_by(user_id: current_user.id) if current_user
    end
    
  end
  
  def new
    @room = current_user.rooms.build
  end
  
  def create
      
     @room = current_user.rooms.build(room_params)
    
    if @room.save
        if params[:images]
            params[:images].each do |i|
              @room.photos.create(image: i)
            end
        end
          @photos = @room.photos
          redirect_to edit_room_path(@room), notice:"votre annonce a été ajouté avec succès"
    else
      render :new
     end
    
  end
  
  def edit
    @photos = @room.photos
  end
  
  def update
      
      if @room.update(room_params)
          if params[:images]
             params[:images].each do |i|
                @room.photos.create(image: i)
             end
          end
        @photos = @room.photos
          redirect_to edit_room_path(@room), notice: "Modification enregistrée ..."
      else
        
        render :edit
      end
    
  end
  
private 
  def set_room
    @room = Room.find(params[:id])
  end
  
 def room_params
      params.require(:room).permit(:home_type, :room_type, :accommodate, :bed_room, :bath_room, 
                                   :listing_name, :summary, :address, :is_wifi, :is_tv, :is_closet, 
                                   :is_shampoo, :is_breakfast, :is_heating, :is_air, :is_kitchen, :price, 
                                   :active)
 end
  
  def require_same_user
 
          if current_user.id != @room.user_id
 
               flash[:danger] = "Vous n'avez pas le droit de modifier cette page"
 
               redirect_to root_path
 
          end
 
 end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
    @rooms = @user.rooms
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def avatar_url(user)
      user.avatar.url
  end
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" 
data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'EKONDA', root_path, { :class=>"navbar-brand" } %>
        </div>
        <div id="navbar" class="navbar-collapse collapse right">
          <ul class="nav navbar-nav navbar-right">
           <li>
 
               <%= link_to new_room_path do %>

               <i class="fa fa-home fa-lg"></i> Devenez hôte

               <% end %>

           </li>
            <% if (!user_signed_in?) %>
                <li><%= link_to 'Inscription', new_user_registration_path %></li>
                <li><%= link_to 'Connexion', new_user_session_path %></li>
                
            <% else %>
            
                <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
              aria-haspopup="true" aria-expanded="false">
                <%= image_tag avatar_url(current_user), class:"img-circle avatar-small" %>  <%= current_user.fullname %>
              <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Mes annonces", rooms_path %></li>
                <li><%= link_to "Mes réservations", your_reservations_path %></li>
                <li><%= link_to "Mes voyages", your_trips_path %></li>
                <li><%= link_to 'Modifier mon profil', edit_user_registration_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'Déconnexion', destroy_user_session_path, 
method: :delete %></li>
              </ul>
            </li>
            <% end %>
            
          </ul>
        </div><!--/.nav-collapse -->
      </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EKONDA</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <%= csrf_meta_tags %>
  
  <meta name="viewport" content="width=device-width, initial-scale=1"> 
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body>

  <%= render 'layouts/navigation' %>
  <%= render 'shared/message' %>
  
  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/pages/home.html.erb
<h2>
  Bienvenue sur notre Ekonda !! 
</h2>

app/views/photos/_list.html.erb
<% if @photos %> 
 
 <div class="row"> 
 
        <% @photos.each do |photo| %> 
 
             <div class="col-md-4"> 
 
                  <div class="panel panel-default"> 
 
                        <div class="panel-heading preview">
 
                             <%= image_tag photo.image.url() %> #on affiche la photo 
 
                        </div>
                        <div class="panel-body">
                          <span class="pull-right">
                            <%= link_to photo, remote: true, method: :delete, data: {confirm: "Certain de vouloir supprimer cette photo"} do %>
                          
                              <i class="fa fa-times fa-lg"></i>
                            
                              <% end %>
                          </span>  
                        </div>
                  </div>
 
             </div>
 
       <% end %>
 
 </div>
 
 <% end %>

app/views/photos/destroy.js.erb
$('#photos').html("<%= j render 'photos/list' %>")

app/views/reservations/_form.html.erb
<%= form_for([@room,  @room.reservations.new]) do |f| %>     
 
    <div class="row">
        <div class="col-md-12 price_tag">
            <span>€ <%= @room.price %></span>
            <span class="pull-right">Par nuit</span>
        </div>
    </div>
     <div class="row">
         <div class="col-md-6">
         <label>Arrivée</label>
         <%= f.text_field :start_date, readonly: 'true', placeholder: 'jj/mm/aaaa', class: 'form-control' %>
         </div>
 
         <div class="col-md-6">
         <label>Départ</label>
         <%= f.text_field :end_date, readonly: 'true', placeholder: 'jj/mm/aaaa', class: 'form-control' %>
         </div>
      </div>
     
     <h5><div id="message"></div></h5> 

      <div id="preview" style="display: none">
           <table class="reservation-table" >
                   <tbody>
                        <tr>
                            <td>Nuit(s)</td>
                            <td><span id="reservation_days"></span></td>
                        </tr>
                        <tr>
                             <td>Total</td>
                             <td><span id="reservation_sum"></span>€</td>
                       </tr>
                   </tbody>
            </table>
     </div>
     <%= f.hidden_field :room_id, value: @room.id %> 
     <%= f.hidden_field :price, value: @room.price %>
     <%= f.hidden_field :total, id: 'reservation_total' %>
     
    <br>
 
     <%= f.submit "Demande de réservation ", class: "btn btn-primary "%>
 
 <% end %>

<script>
    $(function() {
 
       $('#reservation_start_date').datepicker({
                           dateFormat: 'dd-mm-yy',
                           monthNames: ['Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre'],
                          dayNamesMin: ['D', 'L', 'M', 'M', 'J', 'V', 'S']                              
        });
     $('#reservation_end_date').datepicker({
                          dateFormat: 'dd-mm-yy',
                          monthNames: ['Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre'],
                          dayNamesMin: ['D', 'L', 'M', 'M', 'J', 'V', 'S']                                                                             
 
       });
 });
</script>

app/views/reservations/your_reservations.html.erb
<div class="row">
    <div class="col-md-3">
        <ul class="sidebar-list">
            <li class="sidebar-item"><%= link_to "Mes annonces", rooms_path, class:"sidebar-link" %></li>
            <li class="sidebar-item"><%= link_to "Mes réservations", your_reservations_path, class:"sidebar-link active" %></li>
            <li class="sidebar-item"><%= link_to "Mes voyages", your_trips_path, class:"sidebar-link" %></li>
        </ul>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading"> Mes réservations</div>
            <div class="panel-body">
                <% @rooms.each do |room| %>
                <% room.reservations.order("id DESC").each do |reservation| %>
                <div class="row">
                   <div class="col-md-2">
                       Du <%= reservation.start_date.strftime('%d.%m.%y') %> au <%= reservation.end_date.strftime('%d.%m.%y') %>
                   </div>
                   <div class="col-md-6">
                       <%= link_to room_path(reservation.room) do %>
                           <%= image_tag reservation.room.photos[0].image.url(:thumb) if reservation.room.photos.length > 0 %>
                       <% end %>
                   </div>
                   <div class="col-md-2">
                       <%= link_to user_path(reservation.user) do %>
                           <%= image_tag avatar_url(reservation.user), class:"img-circle avatar-medium" %>
                       <% end %>
                   </div>
                   <div class="col-md-2 right">
                       <h4><%= reservation.total %> €</h4>
                   </div>
                </div>
                <hr>
                <% end %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/reservations/your_trips.html.erb
<div class="row">
    <div class="col-md-3">
        <ul class="sidebar-list">
            <li class="sidebar-item"><%= link_to "Mes annonces", rooms_path, class:"sidebar-link" %></li>
            <li class="sidebar-item"><%= link_to "Mes réservations", your_reservations_path, class:"sidebar-link" %></li>
            <li class="sidebar-item"><%= link_to "Mes voyages", your_trips_path, class:"sidebar-link active" %></li>
        </ul>
    </div>
    <div class="col-md-9">
        <div class="panel panel-default">
            <div class="panel-heading"> Mes voyages</div>
            <div class="panel-body">
                <% @trips.order("id DESC").each do |trip| %>
                <div class="row">
                   <div class="col-md-2">
                       Du <%= trip.start_date.strftime('%d.%m.%y') %> au <%= trip.end_date.strftime('%d.%m.%y') %>
                   </div>
                   <div class="col-md-6">
                       <%= link_to room_path(trip.room) do %>
                           <%= image_tag trip.room.photos[0].image.url(:thumb) if trip.room.photos.length > 0 %>
                       <% end %>
                   </div>
                   <div class="col-md-2">
                       <%= link_to user_path(trip.room.user) do %>
                           <%= image_tag avatar_url(trip.room.user), class:"img-circle avatar-medium" %>
                       <% end %>
                   </div>
                   <div class="col-md-2 right">
                       <h4><%= trip.total %> €</h4>
                   </div>
                </div>
                <hr>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/reviews/_form.html.erb
<%= form_for([@room, @room.reviews.new]) do |f| %>
 
        <%= f.text_field :star %>
 
        <%= f.text_field :comment %>
 
        <%= f.hidden_field :room_id, value: @room.id %>
 
        <div class="actions"%>
 
             <%= f.submit %>
 
        </div>
 
 <% end %>

app/views/reviews/_list.html.erb
<% if @reviews.count == 0 %>
 
      <div class="text-center"><h4>Aucun commentaire.</h4></div>
 
 <% else %>
 
      <% @reviews.order("id desc").each do |r| %> 
 
      <hr>
 
      <div class="row">
 
           <div class="col-md-1">
 
                <%= image_tag avatar_url(r.user), class: "img-circle avatar-medium" %>
 
          </div>
 
          <div class="col-md-11">
 
              <div>
 
                 <strong><%= r.user.fullname %> <%= r.star %> </strong>
 
                 <span class="pull-right">
 
                 <%= link_to "Supprimer mon commentaire", [@room, r], method: :delete, data: {confirm: "Etes-vous sûr?"} if current_user && current_user == r.user %>
 
                 </span>
 
              </div>
 
              <div><%= r.created_at.strftime("%d.%m.%y") %></div>
 
              <div><%= r.comment %></div>
 
           </div>
 
        </div>
 
    <% end %>
 
 <% end %>

app/views/rooms/_form.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
        Devenez hôte Ekonda
    </div>
    <div class="panel-body">
        <div class="container">
            
            <%= form_for @room, html: {multipart: true} do |f| %>
                <%= render 'shared/errors' %>
            <div class="row">
                    <div class="col-md-4 select">
                        <div class="form-group">
                            <label>Genre d'habitation</label>
                            <%= f.select :home_type, [["Maison","Maison"], ["Appartement","Appartement"],
                            ["Bed & Breakfast", "Bed & Breakfast"]], id: "home_type", 
                            prompt: "A sélectionner...", class: "form-control" %>
                        </div>
                    </div>
                    
                    <div class="col-md-4 select">
                        <div class="form-group">
                            <label>Type de logement</label>
                            <%= f.select :room_type, [["Logement entier","Logement entier"], ["Chambre privée","Chambre privée"],
                            ["Chambre partagée","Chambre partagée"]],
                            prompt: "A sélectionner...", class: "form-control" %>
                        </div>
                    </div>
                
                    <div class="col-md-4 select">
                        <div class="form-group">
                            <label> Combien de voyageurs ?</label>
                            <%= f.select :accommodate, [["1 voyageur",1], ["2 voyageurs",2],
                            ["3 voyageurs", 3], ["4 voyageurs",4], ["5 voyageurs",5], ["6 voyageurs",6]], 
                            prompt: "A sélectionner...", class: "form-control" %>
                        </div>
                    </div>    
                     
                </div>
                
            <div class="row">
                    <div class="col-md-4 select">
                    <div class="form-group">
                        <label>Chambre(s)</label>
                        <%= f.select :bed_room, [["1 chambre",1], ["2 chambres",2],
                        ["3 chambres", 3], ["4 chambres ou plus",4]], 
                        prompt: "Sélectionner le nombre", class: "form-control" %>
                    </div>
                    </div>
                
                    <div class="col-md-4 select">
                        <div class="form-group">
                            <label>Salle(s) de bain</label>
                            <%= f.select :bath_room, [["1 salle de bain",1], ["2 salles de bain",2],
                            ["3 salles de bain", 3], ["4 salles de bain ou plus",4]], 
                            prompt: "Sélectionner le nombre", class: "form-control" %>
                        </div>
                    </div>
                </div>
                
            <div class="row">
                    <div class="form-group">
                        <label>Donnez un nom au logement</label>
                        <%= f.text_field :listing_name, placeholder: "Titre de l'annonce", class: "form-control" %>
                    </div>
                </div>
                
            <div class="row">
                    <div class="form-group">
                        <label>Résumé</label>
                        <%= f.text_area :summary, rows:4, placeholder: "Décrivez le décor, l'ambiance, ce qui se trouve à proximité, etc...",
                        class: "form-control" %>
                    </div>
                </div>
                
            <div class="row">
                    <div class="form-group">
                        <label>Adresse</label>
                        <%= f.text_field :address, placeholder: "Où est situé votre logement ?", class: "form-control" %>
                    </div>
                </div>
            
          <div class="row">
              <div class="col-md-4">
                <div class="form-group">
                  <span class="btn btn default btn-file">
                    <i class ="fa fa-cloud-upload fa-lg"></i> Téléchargez vos photos !
                    <%= file_field_tag "images[]", type: :file, multiple: true %>
                  </span>
                </div>
            </div>
          </div>
          
          <div id="photos">
            <%= render 'photos/list' %>
          </div>
          
            <div class="row"> 
                <div class="col-md-4">
                    <div class="form-group">
                        <%= f.check_box :is_wifi %> Wifi
                    </div>
                    
                    <div class="form-group">
                        <%= f.check_box :is_tv %> Télévision
                    </div>
                    
                    <div class="form-group">
                        <%= f.check_box :is_closet %> Penderie/Commode
                    </div>
                    
                    <div class="form-group">
                        <%= f.check_box :is_shampoo %> Shampoing
                    </div>
                </div>
                
                <div class="col-md-4">
                    <div class="form-group">
                        <%= f.check_box :is_kitchen %> Cuisine
                    </div>
                    
                    <div class="form-group">
                        <%= f.check_box :is_breakfast %> Petit déjeuner, café, thé
                    </div>
                    
                    <div class="form-group">
                        <%= f.check_box :is_heating %> Chauffage
                    </div>
                    
                    <div class="form-group">
                        <%= f.check_box :is_air %> Climatisation
                    </div>
                </div>
            </div>
                
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label>Prix par nuit</label>
                        <div class="input-group">
                                <%= f.text_field :price, placeholder: "ex: 45€", class: "form-control" %>
                                <div class="input-group-addon">€</div>
                        </div>
                    </div>
                </div>
            </div>
                
            <div class="row">
                <div class="form-group">
                    <%= f.check_box :active %> Annonce active
                </div>
            </div>
                
            <div class="actions">
                      <%= f.submit "Je valide mon annonce", class: "btn btn-primary"%>
            </div>
            <% end %>
            
        </div>
    </div>
</div>

app/views/rooms/edit.html.erb
<%= render 'form' %>

app/views/rooms/index.html.erb
<div class="row">
 
      <div class="col-md-3">
 
            <ul class="sidebar-list">
 
                  <li class="sidebar-item"><%= link_to "Mes annonces", rooms_path, class:"sidebar-link active" %></li>
                  <li class="sidebar-item"><%= link_to "Mes réservations", your_reservations_path, class:"sidebar-link " %></li>
                  <li class="sidebar-item"><%= link_to "Mes voyages", your_trips_path, class:"sidebar-link" %></li>
 
            </ul>
 
       </div>
 
       <div class="col-md-9">
 
            <div class="panel panel-default">
 
                 <div class="panel-heading">Mes annonces
 
                 </div>
 
  
                <div class="panel-body">
 
                      <% @rooms.each do |room| %>
 
                         <div class="row">
 
                                 <div class="col-md-2">
 
                                      <%= image_tag room.photos[0].image.url(:thumb) if room.photos.length > 0 %> 
 
                                 </div>                              
 
                                 <div class="col-md-7">
 
                                        <h4><%= room.listing_name %></h4>
 
                                 </div>                              
 
                                 <div class="col-md-3 right">
 
                                     <%= link_to "Mettre à jour", edit_room_path(room), 
                                                                  class: "btn btn-primary" %>
 
                                 </div>
 
                        </div>
 
                        <hr>
 
                   <% end %>
 
               </div>
 
           </div>
 
     </div>
 
 </div>

app/views/rooms/new.html.erb
<%= render 'form' %>

app/views/shared/_devise_errors.html.erb
<% unless resource.errors.empty? %>
 
 <script type="text/javascript">
 
     <% resource.errors.full_messages.each do |msg| %>
 
               toastr.error('<%= msg %>')
 
     <% end %>
 
 </script>
 
 <% end %>

app/views/shared/_errors.html.erb
<% unless @room.errors.empty? %>
 
 <script type="text/javascript">
 
 <% @room.errors.full_messages.each do |msg| %>
 
 toastr.error('<%= msg %>')
 
 <% end %>
 
 </script>
 
 <% end %>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
    <script type="text/javascript">
        <% flash.each do |f| %>
        <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info')%>
        toastr['<%= type %>']('<%= f[1] %>')
        <% end %>
    </script>


<% end %>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-3">
    <%= image_tag avatar_url(@user), class:"avatar-full" %>
    <div class="pannel panel-default">
      <div class="panel-heading">Vérification</div>
      <div class="panel-body">
        Email: <%= @user.email %> <br>
        Tel: <%= @user.phone_number %>
      </div>
    </div>
  </div>
  <div class="col-md-9">
     <h2> <%=@user.fullname %> </h2>
     <div class="description row-space-3">
       <%=@user.description %>
    </div>
  </div>
  
  <h4>Annonces (<%= @rooms.length %>)</h4><br>
        <div class="row">
            <% @rooms.each do |room| %>
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading preview">
                        <%= image_tag room.photos[0].image.url(:medium) if room.photos.length > 0 %>
                    </div>
                    <div class="panel-body">
                        <%= link_to room.listing_name, room %>
                    </div>
                </div>
            </div>
            <% end %>
        </div>
</div>